name = "C-Tech"
author = "soundgoodizerfan"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "40fcff73c46beb25dbbde926617d42dfe990571810485bb6731c3c896918202d"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
