name = "C-Tech"
author = "soundgoodizerfan"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "420ade8eabf29e40efd33e4681c4ceac4dd1df6e8ad7ef6a8e8c2afdad51dfa7"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
